#include "arduino_secrets.h"
/*
  Sketch generated by the Arduino IoT Cloud Thing "Thermometer"
  https://create.arduino.cc/cloud/things/642dc8bd-8edc-469a-8c27-276398534e2b

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  float attic_temp;
  float attic_temp_mean;
  CloudTemperatureSensor atticTemperature;
  int attic_temp_n;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

/*

  Wemos D1 Mini Pin Connections

  +-----+--------+-------+----------------+
  | Pin | ESP    | Use   |
  +-----+--------+-------+----------------+
  | RST | RST    | Reset |
  +-----+--------+-------+----------------+
  | A0  | A0     | ADC   |
  +-----+--------+-------+----------------+
  | D0  | GPIO16 | WAKE  |
  +-----+--------+-------+----------------+
  | D5  | GPIO14 | SCLK  | LED display DIO
  +-----+--------+-------+----------------+
  | D6  | GPIO12 | MISO  | LED display CLK
  +-----+--------+-------+----------------+
  | D7  | GPIO13 | MOSI  |
  +-----+--------+-------+----------------+
  | D8  | GPIO15 | CS    |
  +-----+--------+-------+----------------+
  | 3V3 | 3.3V   |       |
  +-----+--------+-------+----------------+
  | TX  | GPIO1  | TX    |
  +-----+--------+-------+----------------+
  | RX  | GPIO3  | RX    |
  +-----+--------+-------+----------------+
  | D1  | GPIO5  | SCL   |
  +-----+--------+-------+----------------+
  | D2  | GPIO4  | SDA   | OneWire Bus
  +-----+--------+-------+----------------+
  | D3  | GPIO0  | FLASH |
  +-----+--------+-------+----------------+
  | D4  | GPIO2  | LED   | sync cue
  +-----+--------+-------+----------------+
  | G   | GND    | GND   | ground
  +-----+--------+-------+----------------+
  | 5V  | N/A    | VCC   | LED VCC
  +-----+--------+-------+----------------+

*/

#include "thingProperties.h"
// standard library headers
#include <OneWire.h>
#include <DallasTemperature.h>  // Dallas Temperature Requires OneWire

// define options
#define LED1

// project library headers
#include "led_utils.h"
#include "serial_utils.h"

// Data wire is plugged into port D2 on the Wemos D1 mini
#define ONE_WIRE_BUS 4  // GPIO4 -> D2
#define TEMPERATURE_PRECISION 12

// Setup a oneWire instance to communicate with any OneWire devices (not just Maxim/Dallas temperature ICs)
OneWire oneWire(ONE_WIRE_BUS);

// Pass our oneWire reference to Dallas Temperature.
DallasTemperature sensors(&oneWire);

const int array_size = 5;
DeviceAddress therm[array_size];
int no_therm;      // total number of sensors
int no_therm_sum;  // number of sensors, excluding probe
int idx_probe = -1;

void setup() {
  // initialize on-board LED
  pinMode(LED_BUILTIN, OUTPUT);  // Initialize the LED_BUILTIN pin as an output
  digitalWrite(LED_BUILTIN, LOW);

  serial_init();
  LED_init();

  Serial.println();
  Serial.println(weldiv);
  Serial.println("Dallas Temperature IC Control Library Demo");
  Serial.println(weldiv);

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);

  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
  */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();

  // Start up the library
  sensors.begin();

  // locate devices on the bus
  Serial.print("Locating devices...");
  Serial.print("Found ");
  no_therm = sensors.getDeviceCount();
  no_therm_sum = no_therm;
  Serial.print(no_therm);
  Serial.println(" devices.");

  Serial.print("Checking number of sensors vs array length: ");
  if (no_therm > array_size) {
    Serial.println("ERROR, make array larger!");
  } else {
    Serial.print("OK ");
    Serial.print(no_therm);
    Serial.print(" < ");
    Serial.println(array_size);
  }

  // report parasite power requirements
  Serial.print("Parasite power is: ");
  if (sensors.isParasitePowerMode()) Serial.println("ON");
  else Serial.println("OFF");

  oneWire.reset_search();
  for (int i = 0; i < no_therm; i++) {
    if (!oneWire.search(therm[i])) {
      Serial.print("Unable to find address for sensor ");
      Serial.println(i);
    } else {
      Serial.print("Device ");
      Serial.print(i);
      Serial.print(" Address: ");
      printAddress(therm[i]);
      Serial.println();
    }
  }

  for (int i = 0; i < no_therm; i++) {
    // set the resolution to 9 bit per device
    sensors.setResolution(therm[i], TEMPERATURE_PRECISION);

    Serial.print("Device ");
    Serial.print(i);
    Serial.print(" Resolution: ");
    Serial.print(sensors.getResolution(therm[i]), DEC);
    Serial.println();
  }

  // clear displays
  display.clear();
  digitalWrite(LED_BUILTIN, HIGH);  // Turn the LED off by making the voltage HIGH
}

// function to print a device address
void printAddress(DeviceAddress deviceAddress) {
  for (uint8_t i = 0; i < 8; i++) {
    // zero pad the address if necessary
    if (deviceAddress[i] < 16) Serial.print("0");
    Serial.print(deviceAddress[i], HEX);
  }
}

// function to print the temperature for a device
void printTemperature(DeviceAddress deviceAddress) {
  float tempC = sensors.getTempC(deviceAddress);
  if (tempC == DEVICE_DISCONNECTED_C) {
    Serial.println("Error: Could not read temperature data");
    return;
  }
  Serial.print("Temp C: ");
  Serial.print(tempC);
  Serial.print(" Temp F: ");
  Serial.print(DallasTemperature::toFahrenheit(tempC));
}

// function to print a device's resolution
void printResolution(DeviceAddress deviceAddress) {
  Serial.print("Resolution: ");
  Serial.print(sensors.getResolution(deviceAddress));
  Serial.println();
}

// main function to print information about a device
void printData(DeviceAddress deviceAddress) {
  Serial.print(" Device Address: ");
  printAddress(deviceAddress);
  Serial.print(" ");
  printTemperature(deviceAddress);
  Serial.println();
}

void loop() {
  ArduinoCloud.update();
  // Your code here
  float atempC[array_size];
  float atempF[array_size];
  float tempF_sum = 0;
  float tempF_mean = 0;
  float tempF_std = 0;
  float tempF_var_sum = 0;
  float tempF_var_mean = 0;

  // call sensors.requestTemperatures() to issue a global temperature
  // request to all devices on the bus
  Serial.print("Requesting temperatures... ");
  sensors.requestTemperatures();
  Serial.println("OK");

  // print the device information
  for (int i = 0; i < no_therm; i++) {
    printData(therm[i]);
    atempC[i] = sensors.getTempC(therm[i]);
    atempF[i] = sensors.getTempF(therm[i]);
    if (i != idx_probe) {
      tempF_sum += atempF[i];
    }
  }
  tempF_mean = tempF_sum / no_therm_sum;

  // print average temperature and calculate standard deviation
  if (no_therm_sum > 1) {
    Serial.print("Average temperature = ");
    Serial.print(tempF_mean);
    for (int i = 0; i < no_therm; i++) {
      if (i != idx_probe) {
        tempF_var_sum += sq(atempF[i] - tempF_mean);
      }
    }
    tempF_var_mean = tempF_var_sum / no_therm_sum;
    tempF_std = sqrt(tempF_var_mean);
    Serial.print(" +/- ");
    Serial.print(tempF_std);
    Serial.print(" °F");
    Serial.print(" (N = ");
    Serial.print(no_therm_sum);
    Serial.println(")");
  }
  if (no_therm_sum > 0) {
    // update LED display
    if ((tempF_mean >= 0) && (tempF_mean < 100)) {
      display.setSegments(SEG_degF, 2, 2);
      display.showNumberDec(tempF_mean, false, 2, 0);
    }

    if ((tempF_mean >= 100) || ((tempF_mean < 0) && (tempF_mean > -100))) {
      display.setSegments(SEG_letF, 1, 3);
      display.showNumberDec(tempF_mean, false, 3, 0);
    }

    if (tempF_mean <= -100) {
      display.showNumberDec(tempF_mean, false, 4, 0);
    }
  } else {
    display.setSegments(SEG_bad, 4, 0);
    Serial.println(" No temperature sensors found!");
  }

  delay(PRINT_DELAY);

  atticTemperature = tempF_mean;
}

/*
  Since AtticTempMean is READ_WRITE variable, onAtticTempMeanChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onAtticTempMeanChange() {
  // Add your code here to act upon AtticTempMean change
}
