// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "de530117-eb95-412f-b3cc-82e6110fa19f";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onAtticTempMeanChange();

float attic_temp;
float attic_temp_mean;
CloudTemperatureSensor atticTemperature;
int attic_temp_n;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(attic_temp, READ, 5 * SECONDS, NULL);
  ArduinoCloud.addProperty(attic_temp_mean, READWRITE, 5 * SECONDS, onAtticTempMeanChange);
  ArduinoCloud.addProperty(atticTemperature, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(attic_temp_n, READ, ON_CHANGE, NULL);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
